name: Deploy Vercel CI
on:
    push:
        branches:
            - dev
jobs:
    deploy:
        env:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
            ENVIRONMENT_VARIABLE: ${{ secrets.ENV_TEST }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Deploy to Vercel(Test Environment)
              uses: amondnet/vercel-action@v20
              with:
                  vercel-token: -- # VERCEL_TOKEN
                  github-token: -- # GITHUB_TOKEN
                  vercel-org-id: -- # VERCEL_ORG_ID
                  vercel-project-id: -- # VERCEL_PROJECT_ID
                  scope: -- # VERCEL_ORG_ID
                  working-directory: ./
