name: Web page to Markdown
on:
  issues:
    types:
      - opened
env:
  hasBody: ${{ github.event.issue.body }}
  isIssueTitleFormat: ${{ startsWith(github.event.issue.title, '[Auto]') }}
jobs:
  WebPageToMarkdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ hasBody && isIssueTitleFormat}}
      - name: Crawl pages and generate Markdown files
        if: ${{ hasBody && isIssueTitleFormat}}
        uses: freeCodeCamp-China/article-webpage-to-markdown-action@v1
        with:
          newsLink: '${{ github.event.issue.Body }}'
          ignoreSelector: '.ad-wrapper'
          markDownFilePath: './chinese/articles/'
          githubToken: ${{ github.token }}

      - name: Git Auto Commit
        if: ${{ hasBody && isIssueTitleFormat}}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '${{ github.event.issue.title }}'
          file_pattern: chinese/articles/*.md
          commit_user_name: PageToMarkdown Bot
          commit_user_email: PageToMarkdown-bot@freeCodeCamp.org

      - name: MSg
        if: ${{ !hasBody || !isIssueTitleFormat }}
        shell: bash
        run: |
           echo "This issue does not need to generate a markdown file. Or the description of the issue is empty."
