name: Web page to Markdown
on:
  issues:
    types:
      - opened
env:
  hasBody: ${{ github.event.issue.body }}
  isIssueTitleFormat: ${{ startsWith(github.event.issue.title, '[Auto]') }}
jobs:
  WebPageToMarkdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ env.hasBody && env.isIssueTitleFormat}}
      - name: Crawl pages and generate Markdown files
        if: ${{ env.hasBody && env.isIssueTitleFormat}}
        uses: freeCodeCamp-China/article-webpage-to-markdown-action@v1
        with:
          newsLink: "${{ github.event.issue.Body }}"
          ignoreSelector: ".ad-wrapper"
          markDownFilePath: "./chinese/articles/"
          githubToken: ${{ github.token }}

      - name: Git Auto Commit
        if: ${{ env.hasBody && env.isIssueTitleFormat}}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "${{ github.event.issue.title }}"
          file_pattern: chinese/articles/*.md
          commit_user_name: PageToMarkdown Bot
          commit_user_email: PageToMarkdown-bot@freeCodeCamp.org

      - name: MSg
        shell: bash
        run: |
          echo env.hasBody;
          echo env.isIssueTitleFormat;
          if [ !env.hasBody ]; then
            echo "The description of the issue is empty."
          elif [ !env.isIssueTitleFormat ]; then
            echo "This issue does not need to generate a markdown file."
          fi
