name: Web page to Markdown
on:
  issues:
    types:
      - opened
jobs:
  WebPageToMarkdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event.issue.body && startsWith(github.event.issue.title, '[Auto]') }}
      - name: Crawl pages and generate Markdown files
        if: ${{ github.event.issue.body && startsWith(github.event.issue.title, '[Auto]') }}
        uses: freeCodeCamp-China/article-webpage-to-markdown-action@v1
        with:
          newsLink: "${{ github.event.issue.Body }}"
          ignoreSelector: ".ad-wrapper"
          markDownFilePath: "./chinese/articles/"
          githubToken: ${{ github.token }}

      - name: Git Auto Commit
        if: ${{ github.event.issue.body && startsWith(github.event.issue.title, '[Auto]') }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "${{ github.event.issue.title }}"
          file_pattern: chinese/articles/*.md
          commit_user_name: PageToMarkdown Bot
          commit_user_email: PageToMarkdown-bot@freeCodeCamp.org

      - name: Abnormal hint 1
        if: ${{ !startsWith(github.event.issue.title, '[Auto]') }}
        shell: bash
        run: echo "This issue does not need to generate a markdown file."
      - name: Abnormal hint 2
        if: ${{ !github.event.issue.body }}
        shell: bash
        run: echo "The description of the issue is empty."
