name: Web page to Markdown
on:
  issues:
    types:
      - opened
env:
  issue_body: ${{ github.event.issue.body }}
  issue_title: ${{ github.event.issue.title }}
jobs:
  WebPageToMarkdown:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
        if: ${{ "$issue_body" && startsWith("$issue_title", '[Auto]') }}
      - name: Crawl pages and generate Markdown files
        if: ${{ "$issue_body" && startsWith("$issue_title", '[Auto]') }}
        uses: freeCodeCamp-China/article-webpage-to-markdown-action@v1
        with:
          newsLink: "${{ github.event.issue.Body }}"
          ignoreSelector: ".ad-wrapper"
          markDownFilePath: "./chinese/articles/"
          githubToken: ${{ github.token }}

      - name: Git Auto Commit
        # if: ${{ github.event.issue.body && startsWith(github.event.issue.title, '[Auto]') }}
        if: ${{ "$issue_body" && startsWith("$issue_title", '[Auto]') }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "${{ github.event.issue.title }}"
          file_pattern: chinese/articles/*.md
          commit_user_name: PageToMarkdown Bot
          commit_user_email: PageToMarkdown-bot@freeCodeCamp.org

      - name: Abnormal hint 1
        # if: ${{ !startsWith(github.event.issue.title, '[Auto]') }}
        if: ${{ !startsWith("$issue_title", '[Auto]') }}
        shell: bash
        run: echo "This issue does not need to generate a markdown file."
      - name: Abnormal hint 2
        # if: ${{ !github.event.issue.body }}
        if: ${{ !"$issue_body" }}
        shell: bash
        run: echo "The description of the issue is empty."
